name: Test

# Required to allow sticky-pull-request-comment to work
permissions:
  pull-requests: write

on:
  - pull_request
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: '**/*.md'
      - name: Install Ruby 3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake test
      - name: Build jekyll html
        run: bundle exec rake build
      - uses: actions/upload-artifact@v4
        id: upload-preview
        with:
          name: preview
          path: _site/
          retention-days: 7
          overwrite: true
          compression-level: 9
          if-no-files-found: error
